# Site settings
title: Derek Purdy
description: 'Just another tech guy with my head in the clouds'
url: 'http://www.derekpurdy.com'
# baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: derekpurdy

author:
  name: 'Derek Purdy'
  email: dpurdy@gmail.com
  twitter_username: derekpurdy
  github_username:  derekpurdy
  linkedin_username:  derekpurdy

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
